# .github/workflows/docker-build-push.yml
name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3 # Essential for building ARM images on x86 runners

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Initializes Docker Buildx environment

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get current date for image tag
      id: date
      run: echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ddns:latest
          ${{ secrets.DOCKER_USERNAME }}/ddns:${{ env.DATE }}
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64